a = int(input("Enter a number "))
b = int(input("Enter another number "))
print("Sum of these numbers is ", a+b)
print("Difference of these numbers is ", a-b)
print("Product of these numbers is ", a*b)
print("Division of these numbers is ", a/b)
print("Remainder of these numbers is ", a%b)
print("Floor Division of these numbers is ", a//b)
